export { default as Dashboard } from "./Dashboard/Dashboard";
// export { default as PictroMagic } from './PictroMagic/PictroMagic';
// export { default as PictroAIStudio } from './PictroAIStudio/PictroAIStudio';
// export { default as AIArtGenerator } from './AIArtGenerator';
export { default as PromptGenerator } from "./ArtGenerator/PromptGenerator";
export { default as FromText } from "./ArtGenerator/FromText";
// export { default as TextToPrompt } from './TextToPrompt';
// export { default as ImageToPrompt } from './ImageToPrompt';
// export { default as ImageRemix } from './ImageRemix';
// export { default as Pricing } from './Pricing';
// export { default as Profile } from './Profile';
// export { default as Login } from './Login';
// export { default as SignUp } from './SignUp';
// export { default as ForgetPass } from './ForgetPass';
